# Generated by Django 5.1.6 on 2025-02-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="genre",
            new_name="genres",
        ),
    ]
